Updated the version requirement for paradox to match latest version of mlr3 (1.4.0)
Error: mlr3 requires paradox >= 1.0.1

Updated paradox:
renv::install("paradox@1.0.1")
renv::snapshot()

Installed latest versions of packages required for credit_example.R
renv::install("mlr3")  # version 1.4.0
renv::install("mlr3learners") # version 0.14.0
renv::install("mlr3pipelines") # version 0.10.0