Fixed box overlap function
ERROR: 'list' object cannot be coerced to type 'logical'

New version of paradox changed the internal structure of ParamSet$params (no longer named list), so the previous implementation of test_box1_overlap_box2() which iterated over box$params no longer returned logical values, but sth unexpected

we now iterate over box$ids() and uses public bindings $lower, $upper, $levels, get_domain() instead of accessing $params directly